### PR TITLE
Allow additional floor types

### LINKED ISSUE #321: Allow describing mass floors
Spun off from the discussion in https://github.com/hpxmlwg/hpxml/issues/298.

For multifamily buildings, an apartment floor can be a mass floor instead of a frame floor. Some options for handling this in HPXML:
1. Create a new `MassFloor` element, at the same level as the `FrameFloor` element, with inputs specific to mass floors.
2. Rename the `FrameFloor` element to `Floor` and introduce a `FloorType` child element (similar to [`Wall/WallType`](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Enclosure/Walls/Wall/WallType)).
3. Use the `Slab` element to describe a mass floor? At a minimum, it would need an `ExteriorAdjacentTo` element.

### PR DESCRIPTION
**Pull request by bpark1327**
Fixes #321 

Renames `FrameFloors/FrameFloor` to `Floors/Floor`.
Renames `WallType/StructurallyInsulatedPanel` to `WallType/StructuralInsulatedPanel`
Adds `FloorType` with choices of:
- `WoodFrame`
- `StructuralInsulatedPanel`
- `SteelFrame`
- `SolidConcrete`
- `Other`

### CODE REVIEW

**Comment by bpark1327** [comment]
Some additional thoughts (https://github.com/hpxmlwg/hpxml/pull/327#pullrequestreview-1036434224):

- [ ] How do we specify additional light-weight concrete layer (e.g., gypcrete)?  
- [ ] Can we describe the joist material as metal?
- [ ] Can we describe floor trusses appropriately? Revisit existing FloorJoists and FloorTrusses elements @nmerket

**Comment by RockyMtnBrian** [comment]
Note that "SIP" stands for Structural Insulated Panel, as opposed to "structurally".  If feasible, I suggest eliminating the "ly" part of the FloorType label.

**Comment by shorowit** [comment]
Thanks @RockyMtnBrian, I have fixed this. Because that name was already used for `WallType`, it's a breaking change.

I also discovered that @bpark1327 had added a new data type for floor type, but didn't actually add a FloorType element under Floor that uses it. That's now fixed too.

**Comment by RockyMtnBrian** [comment]
Just a thought, @shorowit:  If there's a need to separately label the SIP wall vs SIP floor, then SIPWall and SIPFloor might do the job.

**Comment by RockyMtnBrian** [comment]
Note that SIPs get used for roofs, too.  SIPRoof?

**Comment by shorowit** [comment]
@RockyMtnBrian There is not a need to distinguish SIP wall from SIP floor -- one will show up as `Wall[WallType/StructuralInsulatedPanel]` and the other will show up as `Floor[FloorType/StructuralInsulatedPanel]`.

For roofs, it looks like the best place to add a SIP option under Roof would be in the [DeckType](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Enclosure/Roofs/Roof/DeckType) element. (RoofType would be most consistent with WallType and FloorType, but unfortunately it's [already used to describe the roofing material](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Enclosure/Roofs/Roof/RoofType).)

**Pull request merged**
