### PR TITLE
Reworking HPXML's Enclosure

### PR DESCRIPTION
**Pull request by shorowit**
(This PR replaces https://github.com/hpxmlwg/hpxml/pull/105, https://github.com/hpxmlwg/hpxml/pull/176, https://github.com/hpxmlwg/hpxml/pull/179, https://github.com/hpxmlwg/hpxml/pull/178, https://github.com/hpxmlwg/hpxml/pull/166, and https://github.com/hpxmlwg/hpxml/pull/113, which are all changes to the Enclosure element.)

This PR is a second attempt to update HPXML's Enclosure element to address several fundamental issues:
1. Difficulty describing attics, both in terms of attached surfaces (e.g., roofs, floors, knee walls, gable walls) as well as the inability to specify multiple floor/roof elements for a given attic. See https://github.com/hpxmlwg/hpxml/issues/102 and https://github.com/hpxmlwg/hpxml/issues/28.
2. Inability to easily describe some building surfaces, such as knee walls between conditioned/unconditioned attic, bonus room floors over garages, above-grade wood frame walls attached to foundations for split-level homes, etc.
3. Confusion over where certain surfaces should be defined. For example, should a foundation wall between conditioned and unconditioned basements be part of the conditioned basement Foundation or unconditioned basement Foundation (or duplicated in both)?

The proposal attempts to minimize the breaking changes relative to HPXML v2.3. 

Breaking changes:
- Replaces AtticsAndRoofs with [Attics/Attic](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Attics/Attic) elements, structured similarly to Foundations/Foundation.
- Moves all surfaces to the Enclosure level. These surfaces can be (optionally) referenced from Foundation, Attic, or Garage elements through, e.g., [Attic/AttachedToWall](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Attics/Attic/AttachedToWall) elements (or similar) with an IDREF.  Thus, a surface can be defined once and referenced from two different Foundation or Attic elements if needed.
- All surfaces have [InteriorAdjacentTo](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Walls/Wall/InteriorAdjacentTo) and [ExteriorAdjacentTo](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Walls/Wall/ExteriorAdjacentTo) fields, except for Roof/Slab elements that do not have ExteriorAdjacentTo. Roofs are always assumed to be exterior adjacent to outside and Slabs are always assumed to be exterior adjacent to ground.
- Replaces the optional AtticType enumeration with a required [AtticType element w/ sub-elements](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Attics/Attic/AtticType), consistent with [FoundationType](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Foundations/Foundation/FoundationType). All existing attic type enumerations can be mapped to the new elements.

New features:
- The [FrameFloor](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor) element can now be used for all floors/ceilings (e.g., attic floors, floors above foundations, floors of bonus rooms, etc.). Added "none" as a [FloorCovering](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/FrameFloors/FrameFloor/FloorCovering) enumeration to describe attic floors.
- Creates a [Garages/Garage](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Garages/Garage) element, structured similarly to Foundations/Foundation.
- Adds [DistanceToTopOfInsulation](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/DistanceToTopOfInsulation) and [DistanceToBottomOfInsulation](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/FoundationWalls/FoundationWall/DistanceToBottomOfInsulation) elements for FoundationWalls. Allows describing, e.g., 4ft high insulation in an 8ft basement.
- Adds an [UnderSlabInsulationSpansEntireSlab](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Slabs/Slab/UnderSlabInsulationSpansEntireSlab) element for the Slab to specify that the under slab insulation spans the entire slab.
- Allows specifying an [Attic/VentilationRate](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Attics/Attic/VentilationRate) and [Foundation/VentilationRate](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Foundations/Foundation/VentilationRate) for vented attics/crawlspaces. Units can be "ACHnatural", "SLA", or "CFM per sq.ft.".
- Extends [SolarAbsorptance](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/SolarAbsorptance) and [Emittance](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/RimJoists/RimJoist/Emittance) elements to RimJoists.

Since a picture is worth a thousand words, here's how the Enclosure looks. Note that some elements were hidden to keep the layout simple to understand. (Or you can view it live on the [HPXML Toolbox website](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure).)

image

### CODE REVIEW

**Comment by shorowit** [comment]
A few discussion items:
- Should HPXML provide guidance for InteriorAdjacentTo and ExteriorAdjacentTo, especially for surfaces between spaces (e.g., knee walls, floors between attic/living, floors between foundation/living, floors under bonus room, walls between living/garage, walls between foundation spaces, etc.)?
- Is it sufficient to simply have `Floor` elements (and not need `Ceiling` elements)?
- Are the correct AttachedtoFoo elements available for Attic/Garage/Foundation elements? Should there be AttachedToRimJoist elements?

**Comment by nmerket** [comment]
@shorowit, thank you for the detailed pull request and explanations of what you've done here. This goes a long way to address some of the inconsistencies and pain points we've experienced and that I've heard from users. 

Some Questions/Comments:

- What is the difference between `FloorTrusses` and `FloorJoists` in `Floor`? I think I understand joists, but not trusses.
- Is there a reason `GarageType` is not required the way `AtticType` and `FoundationType` are?
- In `Foundation` and `Garage` there is a `AttachedToFloor` element referencing a floor. I think these are intended to be floors _above_ the foundation or garage, respectively. If that's the case that should be made clear because the terminology is somewhat confusing. At the very least, it should be mentioned in an annotation on `AttachedToFloor`. We could also consider making it explicit in the element name, i.e. `AttachedToFloorAbove`. I suppose the same thing goes for attics and "below." I'll have to think on that. Leaning towards an annotation to explain the convention.
- An `AttachedToRimJoists` would be useful on the `Foundation` element. 
- Here's a crazy idea for interior surfaces: What if we had `ExteriorAdjacentTo` stay as it is and allow 0 or 1 of them, and allowed 0 to 2 `InteriorAdjacentTo` elements? That way if we had say an attic knee wall, it would use two `InteriorAdjacentTo` elements and no `ExteriorAdjacentTo` elements.

**Comment by shorowit** [comment]
Good comments, @nmerket. Thanks for reviewing.

>     * What is the difference between `FloorTrusses` and `FloorJoists` in `Floor`? I think I understand joists, but not trusses.

I also don't understand why trusses are available. But both joists and trusses are [available in HPXML v2.3](https://hpxml.nrel.gov/datadictionary/2.3.0/Building/BuildingDetails/Enclosure/Foundations/Foundation/FrameFloor), so I retained it.

>     * Is there a reason `GarageType` is not required the way `AtticType` and `FoundationType` are?

Just an oversight. I've changed it to be required.

>     * In `Foundation` and `Garage` there is a `AttachedToFloor` element referencing a floor. I think these are intended to be floors _above_ the foundation or garage, respectively. If that's the case that should be made clear because the terminology is somewhat confusing. At the very least, it should be mentioned in an annotation on `AttachedToFloor`. We could also consider making it explicit in the element name, i.e. `AttachedToFloorAbove`. I suppose the same thing goes for attics and "below." I'll have to think on that. Leaning towards an annotation to explain the convention.

A third possibility would be to revert the name to `Floor` to `FrameFloor`, as that helps distinguish it from `Slab`. That's how it was in HPXML v2.3 of course, with a `Foundation` having a `FrameFloor` and `Slab`. I don't have a strong opinion. I did [document the Floor element](https://hpxml.nrel.gov/datadictionary/3/Building/BuildingDetails/Enclosure/Floors/Floor) though.

>     * An `AttachedToRimJoists` would be useful on the `Foundation` element.

Ok, it's been added.

>     * Here's a crazy idea for interior surfaces: What if we had `ExteriorAdjacentTo` stay as it is and allow 0 or 1 of them, and allowed 0 to 2 `InteriorAdjacentTo` elements? That way if we had say an attic knee wall, it would use two `InteriorAdjacentTo` elements and no `ExteriorAdjacentTo` elements.

Crazy indeed. I see where you're coming from and it has some appeal. That said, I think it would add more effort to any HPXML import code. I'm open to the idea, but probably lean towards not doing this.

**Comment by nmerket** [comment]
## Notes from phone call

- @gamalielL: How does this work for a variety of measures?
   - @nmerket: We should work through several examples of measures. Can people provide some example measures in HPXML?
- @gamalielL: How would this affect the existing use cases?
   - @nmerket: Since there is a mapping from HPXML 2.3 to this for every element, we'd keep the same elements in the use cases. ERI would probably not use the "spaces" much as most of that software is using a surface-based approach.
- @lirainer: Has concerns about the potential for inconsistencies between `(Interior|Exterior)AdjacentTo` and the idrefs. 
- @gamalielL: Add "none" to floor covering for unfinished attics without flooring.
- Stick with `FrameFloor` instead of `Floor`. 
- How to handle Interior and Exterior Adjacent To for surfaces in between to interior spaces?
   - @shorowit: For lack of a strong preference in the group, we'll allow the interior and exterior adjacent to be arbitrary in this case.
- `InsulationHeight` is that from the top or the bottom? We may need a new element measuring the distance to top of insulation and bottom. 
- @gamalielL and Brian: Attic ventilation rate. This should be on the `Attic` element instead of the building summary because a house can have more than one attic with different ventilation rates. 
- @lirainer: Add the enumeration "CFM per sq.ft." to `AtticVentilationRate/UnitofMeasure`.
- `FloorTrusses` could be replaced with an enumeration in `FloorJoists/Material`.

**Comment by shorowit** [comment]
I've updated the PR description to reflect the following changes that I made based on feedback:
- [x] Reverted Floor to FrameFloor.
- [x] Added "none" to FloorCovering for unfinished attics without flooring.
- [x] Changed FoundationWall/InsulationHeight to DistanceToTopOfInsulation and DistanceToBottomOfInsulation.
- [x] Moved ventilation specifications to the Attic/Foundation level. Added the enumeration "CFM per sq.ft." to VentilationRate/UnitofMeasure.

**Comment by nmerket** [comment]
Fixes #28

**Pull request merged**
