### PR TITLE
Heat pump detailed performance inputs

### PR DESCRIPTION
**Pull request by shorowit**
Can accommodate, e.g., cold climate heat pump performance data from the [NEEP database](https://ashp.neep.org) or expanded manufacturer's data.

New schema element proposed under `HeatPump` for heating (similar for cooling):

image

Example product from NEEP:

image

Example HPXML snippet for this product:

```xml
<HeatPump>
    <SystemIdentifier id='HeatPump1'/>
    <DistributionSystem idref='HVACDistribution1'/>
    <HeatPumpType>mini-split</HeatPumpType>
    <HeatPumpFuel>electricity</HeatPumpFuel>
    <HeatingCapacity>16000.0</HeatingCapacity>
    <CoolingCapacity>12000.0</CoolingCapacity>
    <AnnualCoolingEfficiency>
        <Units>SEER</Units>
        <Value>21.3</Value>
    </AnnualCoolingEfficiency>
    <AnnualHeatingEfficiency>
        <Units>HSPF</Units>
        <Value>11.7</Value>
    </AnnualHeatingEfficiency>
    ...
    <CoolingDetailedPerformanceData>
        <PerformanceDataPoint>
            <OutdoorTemperature>82</OutdoorTemperature>
            <IndoorTemperature>80</IndoorTemperature>
            <Capacity>3437</Capacity>
            <CapacityDescription>minimum</CapacityDescription>
            <Efficiency>
                <Units>COP</Units>
                <Value>8.39</Value>
            </Efficiency>
        </PerformanceDataPoint>
        <PerformanceDataPoint>
            <OutdoorTemperature>82</OutdoorTemperature>
            <IndoorTemperature>80</IndoorTemperature>
            <Capacity>15276</Capacity>
            <CapacityDescription>maximum</CapacityDescription>
            <Efficiency>
                <Units>COP</Units>
                <Value>3.2</Value>
            </Efficiency>
        </PerformanceDataPoint>
        <PerformanceDataPoint>
            <OutdoorTemperature>95</OutdoorTemperature>
            <IndoorTemperature>80</IndoorTemperature>
            <Capacity>3100</Capacity>
            <CapacityDescription>minimum</CapacityDescription>
            <Efficiency>
                <Units>COP</Units>
                <Value>7.57</Value>
            </Efficiency>
        </PerformanceDataPoint>
        <PerformanceDataPoint>
            <OutdoorTemperature>95</OutdoorTemperature>
            <IndoorTemperature>80</IndoorTemperature>
            <Capacity>13600</Capacity>
            <CapacityDescription>maximum</CapacityDescription>
            <Efficiency>
                <Units>COP</Units>
                <Value>2.75</Value>
            </Efficiency>
        </PerformanceDataPoint>
    </CoolingDetailedPerformanceData>
    <HeatingDetailedPerformanceData>
        <PerformanceDataPoint>
            <OutdoorTemperature>5</OutdoorTemperature>
            <IndoorTemperature>70</IndoorTemperature>
            <Capacity>2671</Capacity>
            <CapacityDescription>minimum</CapacityDescription>
            <Efficiency>
                <Units>COP</Units>
                <Value>4.89</Value>
            </Efficiency>
        </PerformanceDataPoint>
        <PerformanceDataPoint>
            <OutdoorTemperature>5</OutdoorTemperature>
            <IndoorTemperature>70</IndoorTemperature>
            <Capacity>16710</Capacity>
            <CapacityDescription>maximum</CapacityDescription>
            <Efficiency>
                <Units>COP</Units>
                <Value>2.37</Value>
            </Efficiency>
        </PerformanceDataPoint>
        <PerformanceDataPoint>
            <OutdoorTemperature>17</OutdoorTemperature>
            <IndoorTemperature>70</IndoorTemperature>
            <Capacity>2824</Capacity>
            <CapacityDescription>minimum</CapacityDescription>
            <Efficiency>
                <Units>COP</Units>
                <Value>5.52</Value>
            </Efficiency>
        </PerformanceDataPoint>
        <PerformanceDataPoint>
            <OutdoorTemperature>17</OutdoorTemperature>
            <IndoorTemperature>70</IndoorTemperature>
            <Capacity>17600</Capacity>
            <CapacityDescription>maximum</CapacityDescription>
            <Efficiency>
                <Units>COP</Units>
                <Value>2.62</Value>
            </Efficiency>
        </PerformanceDataPoint>
        <PerformanceDataPoint>
            <OutdoorTemperature>47</OutdoorTemperature>
            <IndoorTemperature>70</IndoorTemperature>
            <Capacity>3100</Capacity>
            <CapacityDescription>minimum</CapacityDescription>
            <Efficiency>
                <Units>COP</Units>
                <Value>6.49</Value>
            </Efficiency>
        </PerformanceDataPoint>
        <PerformanceDataPoint>
            <OutdoorTemperature>47</OutdoorTemperature>
            <IndoorTemperature>70</IndoorTemperature>
            <Capacity>19400</Capacity>
            <CapacityDescription>maximum</CapacityDescription>
            <Efficiency>
                <Units>COP</Units>
                <Value>3.09</Value>
            </Efficiency>
        </PerformanceDataPoint>
    </HeatingDetailedPerformanceData>
</HeatPump>
```

### CODE REVIEW

**Comment by RockyMtnBrian** [comment]
Does this allow for a variable number of PerformanceDataPoints?  It appears it might, which seems beneficial for products that may rate the equipment at more extreme temperatures.  Such flexibility may also prove helpful as this HP market segment evolves and standardizes.

Is it essential to collect PerformanceDataPoints for both the maximum and minimum capacity?  If a user is only interested in the minimum ("worst-case") values, are those sufficient?

Offering this capability meets an urgent and growing need in the marketplace, as more jurisdictions set policies to decarbonize.  I strongly support this proposal.

**Comment by shorowit** [comment]
That said, it's common practice to have HPXML schema fields almost always specified as optional to support multiple use cases. But for any specific use case, some of the optional fields may be required. For example, the current RESNET proposal for ERI is to collect both min and max capacities/COPs for all 5 NEEP datapoints, so the fields would be required for that use case.

**Comment by shorowit** [comment]
- Include indoor wetbulb for performance data points.
- WG is generally okay with normalized capacities
- Add (0 to many) ExternalResource elements to individual data point elements
- WG suggests adding the datapoint elements to heating and cooling systems too
- Would be interesting to see how this could apply to other HVAC system types (like a boiler)

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-12-06](https://youtu.be/XAoF-bLamro?t=1949)

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2023-01-10](https://youtu.be/bSDTeVFTOPQ?t=176)

**Pull request merged**
