### PR TITLE
Add Walkout basement element

### PR DESCRIPTION
**Pull request by shorowit**
Adds a `Walkout` boolean element for the basement foundation type.

image

### CODE REVIEW

**Comment by nmerket** [comment]
Wouldn't any garage that's a foundation be a "walk out"? If you can drive out of it, you can walk out of it. We could use some more clarification of when this would be used and if it's needed.

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2023-06-13](https://youtu.be/OOTH1_Ahcvs?t=177)

**Comment by shorowit** [comment]
Update description to refer to a door directly on grade (so as to exclude doors that have stairs to the ground).

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2023-07-11](https://youtu.be/0vfe3srBLts?t=355)

**Pull request merged**
