### PR TITLE
Generalize space heater element

### PR DESCRIPTION
**Pull request by shorowit**
Replaces `PortableHeater` with `SpaceHeater` so as to accommodate fixed (non-portable) space heaters too. Space heaters may be vented or unvented.

### CODE REVIEW

**Comment by shorowit** [comment]
- [ ] Change `PortableHeater` to `SpaceHeater` and add `Portable` (boolean) sub element

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2023-07-11](https://youtu.be/0vfe3srBLts?t=1685)

**Comment by nmerket** [comment]
Remove `Portable` for now in case we want to do it as enumerations as in #240 with the `RoomCoolingType`.

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2023-08-08](https://youtu.be/cS41gQ6gEM8?t=1793)

**Pull request merged**
