### PR TITLE
New `CFISControls`

### LINKED ISSUE #330: Additional CFIS elements
There are several control strategies related to central fan integrated supply (CFIS) mechanical ventilation systems that it would be nice to describe in an HPXML file.

Here's a strawman proposal:
- `CFISControls` (to be used when `FanType`="central fan integrated supply")
  - `HasOutdoorAirControl`: boolean (if true, prevents excess ventilation during hours of significant HVAC runtime)
  - `AdditionalRuntimeOperatingMode`: "none", "air handler", or "supplemental fan" (describes if/how the CFIS system provides additional ventilation beyond when the HVAC system is running to meet a given ventilation requirement/target)
  - `SupplementalFan`: idref to another `VentilationFan` (to be used when `AdditionalRuntimeOperatingMode`="supplemental fan")

There is also a control strategy where an exhaust supplemental fan can run simultaneously with the air handler fan (to produce balanced ventilation), but that might be getting too detailed and should be handled by an `extension` element...?

### PR DESCRIPTION
**Pull request by shorowit**
Closes #330.

Adds a new CFISControls element under `VentilationFan:
- `CFISControls` (Relevant when FanType="central fan integrated supply".)
  - `HasOutdoorAirControl`: boolean (Has controls to block the flow of outside air when the CFIS system is not ventilating. For example, an electronically-controlled mechanical damper, or an in-line fan that substantially blocks the flow when not running.)
  - `AdditionalRuntimeOperatingMode`: "none", "air handler fan", "supplemental fan", or "other" (Describes if/how the CFIS system provides additional ventilation beyond when the HVAC system is running to meet a given ventilation target.)
  - `SupplementalFan`: idref` (When AdditionalRuntimeOperatingMode="supplemental fan", specifies the VentilationFan that serves as that supplemental fan.)
  - `extension`

### CODE REVIEW

**Comment by shorowit** [comment]
Consider adding an element to describe when the supplemental fan provides balanced airflow (in conjunction with the air handler supply airflow).

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-10-11](https://youtu.be/YSbsZ_VTfHY?t=1837)

**Comment by RockyMtnBrian** [comment]
Balancing the outside air flowrate via the Air Handler by using a supplemental fan is a relatively difficult real-world scenario.  Matching the actual flowrates between radically different fans (e.g. air handler plus bathroom exhaust) is probably accidental at best.  
To assess this in the real world, both flows must be measured, and both fans must operate simultaneously.

**Comment by shorowit** [comment]
Good feedback, @RockyMtnBrian. I'm inclined not to add another element to try to describe this case. Software tools can use an `extension` element for the time being, and we can always revisit adding a new element to HPXML in the future if there is significant interest.

**Pull request merged**
