### PR TITLE
Buried ducts

### LINKED ISSUE #374: Allow describing buried ducts
Related issue: https://github.com/hpxmlwg/hpxml/issues/195

### PR DESCRIPTION
**Pull request by shorowit**
image

New `DuctBuriedInsulationLevel` element with choices of:
- not buried
- partially buried
- fully buried
- deeply buried

Description of element: "Describes ducts buried in, e.g., attic loose-fill insulation. Partially buried ducts have insulation that does not cover the top of the ducts. Fully buried ducts have insulation that just covers the top of the ducts. Deeply buried ducts have insulation that continues above the top of the ducts. See https://basc.pnnl.gov/resource-guides/ducts-buried-attic-insulation for more information."

Also:
- Updates `DuctInsulationRValue` description: "This should exclude the exterior air film -- e.g., use zero for uninsulated ducts. For ducts buried in insulation, this should only represent any surrounding insulation duct wrap and not the entire attic insulation R-value."
- Adds a `DuctEffectiveRValue` element with description: "The overall effective R-value. Includes the exterior air film as well as other effects such as adjustments for insulation wrapped around round ducts, or ducts buried in attic insulation."

Closes #374.

### CODE REVIEW

**Comment by shorowit** [comment]
- Reformulate to be more specific to buried duct scenario. Could be multiple inputs (presence, how deep, etc.).

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2023-03-14](https://youtu.be/alTvyoUs2qk?t=1107)

**Comment by shorowit** [comment]
Address todo item above, then mark as merge.

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2023-05-09](https://youtu.be/62BxnKveGro?t=782)

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2023-06-13](https://youtu.be/OOTH1_Ahcvs?t=689)

**Pull request merged**
