### PR TITLE
Adds `FrameFloor/FloorOrCeiling` element

### LINKED ISSUE #253: Introduce Ceilings element?
As part of https://github.com/hpxmlwg/hpxml/pull/181, it was debated whether to introduce `Ceilings` (or `FrameCeilings`) as a separate element from `FrameFloors`. It was not included at the time, partly because the difference between ceiling and floor is one of perspective (e.g., the attic floor is the living space's ceiling).

However, there are times where you can't tell whether a `FrameFloor` is a ceiling or floor. The best example is, e.g., InteriorAdjacentTo='living space' and ExteriorAdjacentTo='other housing unit' for a multifamily unit. This surface could be a floor where the other unit is below the current unit, or a ceiling where the other unit is above the current unit. 

Having separate `Ceiling` and `FrameFloor` elements would solve this. 

However, having two elements could also create additional complexity for software developers. Unless additional changes are made, some surfaces could now be described in two ways. For example, the surface between living space and attic could be described as:
- `Ceiling` with InteriorAdjacentTo=living space and ExteriorAdjacentTo=attic, or
- `FrameFloor` with InteriorAdjacentTo=attic and ExteriorAdjacentTo=living space

To address this, we could consider having two different AdjacentTo enumeration lists -- one for InteriorAdjacentTo that includes 'living space' and one for ExteriorAdjacentTo that _excludes_ 'living space'. This would help to ensure that surfaces adjacent to living space are consistently described from the living space perspective.

### PR DESCRIPTION
**Pull request by shorowit**
Closes #253. Adds `Floor/FloorOrCeiling`: string (choices: "floor", "ceiling"). From the perspective of the living/conditioned space. Often it can be inferred from other information in the HPXML, but not always. This is particularly useful because a lot of standards (like IECC, ANSI 301, etc.) refer to ceilings and floors.

(I'm not calling it `FloorType` because that is being used [here](https://github.com/hpxmlwg/hpxml/pull/332) to support wood frame floors vs mass floors vs ...).

This is a far simpler implementation than [adding an `Enclosure/Ceilings` element](https://github.com/hpxmlwg/hpxml/pull/264), which would require a lot of software updates. 

Should we also deprecate (or mark as deprecated) the "other housing unit above" and "other housing unit below" AdjacentTo enumerations? This is a more flexible implementation and can be used for adjacent locations other than just "other housing unit".

### CODE REVIEW

**Comment by shorowit** [comment]
One comment from WG: While we are changing FrameFloor to Floor, rename to a more generic term?

**Comment by lirainer** [comment]
> One comment from WG: While we are changing FrameFloor to Floor, rename to a more generic term?
Others have struggled with this: https://english.stackexchange.com/questions/191958/is-there-a-common-word-for-floor-and-ceiling

**Comment by nmerket** [comment]
:movie_camera: [Discussion in HPXML Working Group Meeting 2022-10-11](https://youtu.be/YSbsZ_VTfHY?t=2721)

**Comment by RockyMtnBrian** [comment]
I like this idea!!

**Pull request merged**
